"""Gemini-powered Roman Hindi/Hinglish Shayari generator.

Gemini is used ONLY for generating Shayari.
Titles, descriptions, tags, hashtags, SEO keywords and queries
are NEVER generated by Gemini.

The module automatically switches between configured Gemini models
when one model fails or is unavailable.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from google import genai


# ============================================================
# PATHS
# ============================================================

ROOT_DIR = Path(__file__).resolve().parent.parent

HISTORY_FILE = ROOT_DIR / "content_history.json"


# ============================================================
# GEMINI MODEL CONFIGURATION
# ============================================================

# Models are tried in this order.
#
# Example:
# 1. gemini-3.6-flash
# 2. gemini-3.6-flash-lite
# 3. gemini-2.5-flash
#
# If the first model fails, the next model is automatically tried.

DEFAULT_MODELS = [
    "gemini-3.6-flash",
    "gemini-3.6-flash-lite",
    "gemini-2.5-flash",
]


def get_models() -> list[str]:
    """Return Gemini models configured through GEMINI_MODELS.

    Environment example:

        GEMINI_MODELS=gemini-3.6-flash,gemini-3.6-flash-lite,gemini-2.5-flash

    If GEMINI_MODELS is not provided, DEFAULT_MODELS are used.
    """

    raw_models = os.getenv("GEMINI_MODELS", "").strip()

    if not raw_models:
        return DEFAULT_MODELS.copy()

    models = [
        model.strip()
        for model in raw_models.split(",")
        if model.strip()
    ]

    # Remove duplicates while preserving order.
    models = list(dict.fromkeys(models))

    return models or DEFAULT_MODELS.copy()


# ============================================================
# LOCAL FALLBACK SHAYARI
# ============================================================

# These are used only if ALL Gemini models fail.
#
# IMPORTANT:
# They do not generate metadata.
# They are only emergency Shayari content.

FALLBACK_SHAYARI = [
    (
        "Kabhi khamoshi bhi bahut kuch keh jaati hai,\n"
        "jo baat lafzon se na ho,\n"
        "woh aankhon mein reh jaati hai."
    ),

    (
        "Waqt badla, log badle,\n"
        "rishte bhi badal gaye,\n"
        "bas kuch yaadein thi,\n"
        "jo dil mein wahi reh gaye."
    ),

    (
        "Jise dil se chaha,\n"
        "usse bhulana aasaan nahi,\n"
        "kuch log door hokar bhi,\n"
        "kabhi anjaan nahi."
    ),

    (
        "Har muskurahat ke peeche,\n"
        "ek kahani hoti hai,\n"
        "har khamoshi mein bhi,\n"
        "koi baat purani hoti hai."
    ),
]


# ============================================================
# GEMINI CLIENT
# ============================================================

def get_client() -> genai.Client:
    """Create and return Gemini client."""

    api_key = os.getenv("GOOGLE_API_KEY", "").strip()

    if not api_key:
        raise RuntimeError(
            "GOOGLE_API_KEY environment variable is missing."
        )

    return genai.Client(api_key=api_key)


# ============================================================
# HISTORY
# ============================================================

def load_history() -> list[dict[str, Any]]:
    """Load previously generated Shayari history."""

    if not HISTORY_FILE.exists():
        return []

    try:
        data = json.loads(
            HISTORY_FILE.read_text(encoding="utf-8")
        )

        if isinstance(data, list):
            return data

        if isinstance(data, dict):
            items = data.get("items")

            if isinstance(items, list):
                return items

    except Exception as exc:
        print(
            f"Warning: could not read content history: "
            f"{exc}"
        )

    return []


def save_history(item: dict[str, Any]) -> None:
    """Append a generated item to content history."""

    history = load_history()

    history.append(item)

    # Keep only the latest 500 entries.
    history = history[-500:]

    HISTORY_FILE.write_text(
        json.dumps(
            history,
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )


# ============================================================
# RESPONSE PARSER
# ============================================================

def _parse_shayari_response(response: Any) -> str:
    """Extract Shayari text from Gemini response.

    Gemini is requested to return JSON:

        {
            "shayari": "..."
        }

    But this parser also handles plain text responses safely.
    """

    text = getattr(response, "text", "") or ""

    text = text.strip()

    if not text:
        raise RuntimeError(
            "Gemini returned an empty response."
        )

    # --------------------------------------------------------
    # Remove Markdown code fences if Gemini returns them.
    # --------------------------------------------------------

    if text.startswith("```"):

        text = text.strip("`").strip()

        if text.lower().startswith("json"):
            text = text[4:].strip()

    # --------------------------------------------------------
    # Try JSON first.
    # --------------------------------------------------------

    try:

        data = json.loads(text)

        if isinstance(data, dict):

            shayari = str(
                data.get("shayari", "")
            ).strip()

            if shayari:
                return shayari

    except json.JSONDecodeError:
        pass

    # --------------------------------------------------------
    # If JSON parsing fails, use plain response.
    # --------------------------------------------------------

    if text:
        return text

    raise RuntimeError(
        "Gemini returned empty Shayari."
    )


# ============================================================
# PROMPT
# ============================================================

GENERATION_PROMPT = """
Write ONE original Roman Hindi/Hinglish shayari for a YouTube Short.

IMPORTANT:
You are ONLY responsible for writing the Shayari.

DO NOT generate:
- title
- video title
- description
- hashtags
- tags
- keywords
- SEO
- search queries
- captions
- explanations
- metadata

STYLE:
- Write in Roman Hindi/Hinglish only.
- Never use Devanagari.
- Make it emotional and poetic.
- Make it natural and human-sounding.
- Suitable for a Shayari/poetry YouTube Short.
- Avoid generic AI-sounding phrases.
- Avoid unnecessary English.
- Keep the Shayari concise.
- Write 4 to 8 short lines.
- Lines should look good when displayed as poetry on a vertical video.

OUTPUT:
Return JSON only.

Exactly this format:

{"shayari":"line 1\\nline 2\\nline 3\\nline 4"}

Do not add Markdown.
Do not add code fences.
Do not add anything outside the JSON.
""".strip()


# ============================================================
# GEMINI GENERATION
# ============================================================

def generate_shayari() -> dict[str, str]:
    """Generate one Shayari using automatic Gemini model fallback.

    Returns:

        {
            "shayari": "..."
        }

    This function intentionally accepts NO title argument so it
    remains compatible with the existing main.py.
    """

    client = get_client()

    models = get_models()

    errors: list[str] = []

    print()
    print("=" * 60)
    print("🤖 GEMINI SHAYARI GENERATION")
    print("=" * 60)
    print(f"Models configured: {', '.join(models)}")
    print()

    # --------------------------------------------------------
    # Try every configured Gemini model.
    # --------------------------------------------------------

    for index, model in enumerate(models, start=1):

        print(
            f"🔄 Gemini model attempt "
            f"{index}/{len(models)}: {model}"
        )

        try:

            response = client.models.generate_content(
                model=model,
                contents=GENERATION_PROMPT,
            )

            shayari = _parse_shayari_response(
                response
            )

            # ------------------------------------------------
            # Basic validation.
            # ------------------------------------------------

            shayari = shayari.strip()

            if not shayari:
                raise RuntimeError(
                    "Generated Shayari is empty."
                )

            print(
                f"✅ Gemini generation successful "
                f"using: {model}"
            )

            print("=" * 60)
            print()

            return {
                "shayari": shayari
            }

        except Exception as exc:

            error_message = (
                str(exc)
                .replace("\n", " ")
                .strip()
            )

            # Prevent extremely long logs.
            if len(error_message) > 500:
                error_message = (
                    error_message[:500] + "..."
                )

            errors.append(
                f"{model}: {error_message}"
            )

            print(
                f"❌ Gemini model failed: {model}"
            )

            print(
                f"   Error: {error_message}"
            )

            # ------------------------------------------------
            # Automatically switch to next model.
            # ------------------------------------------------

            if index < len(models):

                next_model = models[index]

                print()
                print(
                    f"➡️ Automatically switching "
                    f"to next model: {next_model}"
                )
                print()

    # ========================================================
    # ALL MODELS FAILED
    # ========================================================

    print()
    print("=" * 60)
    print("⚠️ ALL GEMINI MODELS FAILED")
    print("=" * 60)

    for error in errors:
        print(f"- {error}")

    print()
    print(
        "🛟 Using local fallback Shayari."
    )
    print("=" * 60)
    print()

    return local_fallback(
        load_history()
    )


# ============================================================
# LOCAL FALLBACK
# ============================================================

def local_fallback(
    history: list[dict[str, Any]] | None = None,
) -> dict[str, str]:
    """Return an unused local fallback Shayari.

    Attempts to avoid repeating a fallback Shayari that already
    exists in content_history.json.
    """

    history = history or []

    used_shayari = {
        str(item.get("shayari", "")).strip()
        for item in history
        if isinstance(item, dict)
    }

    # --------------------------------------------------------
    # Find first unused fallback.
    # --------------------------------------------------------

    for text in FALLBACK_SHAYARI:

        cleaned = text.strip()

        if cleaned not in used_shayari:

            return {
                "shayari": cleaned
            }

    # --------------------------------------------------------
    # If all fallbacks were used, cycle back to first.
    # --------------------------------------------------------

    return {
        "shayari": FALLBACK_SHAYARI[0].strip()
    }


# ============================================================
# OPTIONAL SAFE HELPER
# ============================================================

def validate_shayari(shayari: str) -> str:
    """Clean and validate Shayari before video generation."""

    if not isinstance(shayari, str):
        raise TypeError(
            "Shayari must be a string."
        )

    shayari = shayari.strip()

    if not shayari:
        raise ValueError(
            "Shayari cannot be empty."
        )

    return shayari


# ============================================================
# MODULE TEST
# ============================================================

if __name__ == "__main__":

    print()
    print("Testing Shayari generator...")
    print()

    try:

        result = generate_shayari()

        print("Generated Shayari:")
        print("-" * 40)
        print(result["shayari"])
        print("-" * 40)

    except Exception as exc:

        print(
            f"Generator error: {exc}"
        )
        raise
